### PR TITLE
Feature/beauty docsy

### PR DESCRIPTION
**Pull request by soutobias**
I've made several enhancements to the website, including:

1. Adjusted the title font for better readability.
2. Revised the banner background by adding opacity to improve its legibility with text overlaid.
3. Streamlined the "about" and "community" pages, transferring all relevant information to the main page. Navigation links in the navbar now guide users to specific sections based on their corresponding "id."
4. Removed all references to Docsy for a cleaner and more tailored look.
5. Introduced fresh content related to the project, with the possibility of offering more comprehensive descriptions of the package's features and capabilities in the "About" section.
6. Included license information in the footer of the website.
7. Regarding the "Getting Started at Liverpool" section, I've removed it from the documentation. I've created a temporary page on the [NOC Intranet](https://nocacuk.sharepoint.com/sites/DigitalOcean/SitePages/COAsT-Installation-on-Liverpool-Servers.aspx) and added this link to the "Getting Started" page. Please note that we may need to update this link in the future.
8. As I made some modifications to the Docsy theme, I've copied certain Docsy partials to the main repository, specifically the footer and header.
9. Additionally, I've included new CSS classes and images in the repository's assets. Some adjustments to the Docsy CSS were necessary to implement these changes effectively.
10. I also updated the install instructions on the README file.

### CODE REVIEW

**Comment by soutobias** [comment]
https://github.com/British-Oceanographic-Data-Centre/COAsT/issues/603

**Review by jpolton — APPROVED** [review]
Fantastic!
@soutobias : could you add a new ticket to review the content of the COAsT/README file

**Comment by soutobias** [comment]
I conducted a comprehensive documentation review, drawing inspiration from similar Python packages in the oceanography domain, such as [argopy](https://argopy.readthedocs.io/en/latest/) and [folium](https://python-visualization.github.io/folium/latest/). My goal was to incorporate best practices and ideas from these related packages into COAsT documentation.

Here are the main changes I made:

1. **Documentation Structure**: I reorganized the documentation by adjusting section names and providing more detailed descriptions for several sections.

2. **Package Overview**: I expanded the content in the Overview section to include more information about the package's functionalities.

3. **Contributing Guidelines**: I reformulate the `contributing` section, adding a `Bug Report` subsection, and consolidating information related to contributing to both the documentation and the package itself. Additionally, I included comprehensive instructions on opening issues and asking questions in discussions.

4. **General Information**: I found that the contribution section contained diverse information that wasn't closely related. To address this, I introduced a new section named `General Information`, which encompasses topics like `Logging`, `Lazy`, `Dask`, `Build Tests`, and `Github Actions Workflow`.

5. **API References**: To address an issue where a class named `index` was causing problems with the documentation rendering,  I added a command to the docstring workflow to rename `index.md` to `index_class.md`. I also renamed the `References` section to `API References`.

6. **Installation Instructions**: I provided additional details in the installation section, both for the package and the documentation. Moreover, I included more comprehensive instructions for the `Build Test` section.

7. **Remote Datasets**: I identified an issue with the `remote datasets` section in the `examples`. Although I tried to run the codes locally, I encountered an error, specifically, "AttributeError: You cannot set the charset when no content-type is defined." As a temporary measure, I retained this section in the project but hid it from the sidebar until further investigation and potential correction.

8. **Logging**: I updated the `logging` section to address a discrepancy. While the documentation stated that the default logging level is "DEBUG," the actual code indicated "CRITICAL." I aligned the documentation with the code by correcting this inconsistency.

@jpolton , could you please check if you agree with these changes.

**Comment by jpolton** [comment]
@soutobias these edits are really great. (I've added a few minor tweaks to the branch). I will look at the `remote datasets problem` now

**Pull request merged**
