### PR TITLE
changes made while looking over site

### PR DESCRIPTION
**Pull request by thogar-computer**
@davbyr @jpolton @anwiseNOCL 
some changes made to the docy site

### CODE REVIEW

**Comment by thogar-computer** [comment]
@davbyr @jpolton @anwiseNOCL 
added in the Dask page now as well

**Comment by thogar-computer** [comment]
@jpolton i have added an example of a photo into the dask page, this required a little page rewiring under the hood. i.e you need to make a page bundle - https://www.docsy.dev/docs/adding-content/content/#page-bundles

**Comment by jpolton** [comment]
> @jpolton i have added an example of a photo into the dask page, this required a little page rewiring under the hood. i.e you need to make a page bundle - https://www.docsy.dev/docs/adding-content/content/#page-bundles

I see. Clever! I will give it a go.

**Review by jpolton — APPROVED** [review]
This is helpful and usefully concise. Thanks

**Review by davbyr — APPROVED** [review]
Looks great and useful 👍

**Pull request merged**
